begin;

create table if not exists public.simulation_catalog_prices (
  id uuid primary key default gen_random_uuid(),
  datasul_code text not null,
  sku text not null,
  volume integer not null,
  catalog_cost numeric default 0,
  catalog_price numeric default 0,
  catalog_gross_price numeric default 0,
  catalog_margin numeric default 0,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null,
  unique (datasul_code, volume)
);

alter table public.simulation_catalog_prices
  add constraint if not exists simulation_catalog_prices_volume_check
  check (volume in (1000, 3000, 5000));

alter table public.simulation_catalog_prices enable row level security;

drop policy if exists "simulation catalog select auth" on public.simulation_catalog_prices;
drop policy if exists "simulation catalog insert auth" on public.simulation_catalog_prices;
drop policy if exists "simulation catalog update auth" on public.simulation_catalog_prices;

create policy "simulation catalog select auth"
  on public.simulation_catalog_prices
  for select
  using (auth.role() = 'authenticated');

create policy "simulation catalog insert auth"
  on public.simulation_catalog_prices
  for insert
  with check (auth.role() = 'authenticated');

create policy "simulation catalog update auth"
  on public.simulation_catalog_prices
  for update
  using (auth.role() = 'authenticated');

alter table public.simulations_history
  add column if not exists simulation_number bigint generated by default as identity,
  add column if not exists datasul_code text,
  add column if not exists volume integer,
  add column if not exists client_name text,
  add column if not exists target text,
  add column if not exists observations text,
  add column if not exists catalog_cost numeric,
  add column if not exists catalog_price numeric,
  add column if not exists catalog_gross_price numeric,
  add column if not exists catalog_margin numeric;

create unique index if not exists idx_simulations_history_simulation_number
  on public.simulations_history(simulation_number);

alter table public.simulations_history
  add constraint if not exists simulations_history_volume_check
  check (volume is null or volume in (1000, 3000, 5000));

create or replace function public.update_simulation_catalog_prices_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists trg_update_simulation_catalog_prices_updated_at on public.simulation_catalog_prices;
create trigger trg_update_simulation_catalog_prices_updated_at
before update on public.simulation_catalog_prices
for each row
execute function public.update_simulation_catalog_prices_updated_at();

commit;
